# Generated by Django 4.2.13 on 2024-06-29 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Temperature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('outside', 'Outside'), ('inside', 'Inside')], max_length=10)),
                ('temperature', models.FloatField()),
                ('date', models.DateField()),
            ],
        ),
    ]
