# Generated by Django 4.2.13 on 2024-06-30 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_chatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='temperature',
            name='humidity',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='temperature',
            name='pressure',
            field=models.FloatField(null=True),
        ),
    ]
