name: Django CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.7, 3.8, 3.9]

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Tests
      run: |
        python manage.py test

    - name: Run Migrations
      run: |
        python manage.py migrate

    - name: Start Django Server
      run: |
        python manage.py runserver 0.0.0.0:8000 &
      env:
        DJANGO_SETTINGS_MODULE: meteo_app.settings
        # Adaugă alte variabile de mediu necesare aici, de exemplu:
        # DATABASE_URL: ${{ secrets.DATABASE_URL }}
        # SECRET_KEY: ${{ secrets.SECRET_KEY }}
